name: Update Clash.yaml

on:
  push:
    branches:
      - main  # Или другая ветка, где лежит ваш файл list.lst

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PyYAML
      run: pip install pyyaml

    - name: Convert list.lst to Clash.yaml
      run: python generate_clash.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add Clash.yaml
        git commit -m "Update Clash.yaml from list.lst"
        git push
