name: Update Gist with Blacklist

on:
  push:
    paths:
      - Blacklist.conf

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Gist with new blacklist.conf
      run: |
        curl -X POST "https://api.github.com/gists/7a0cda49a43f975059d20c86a383dbec" \
        -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
        -d @- << EOF
        {
          "files": {
            "Blacklist.conf": {
              "content": "$(cat blacklist.conf)"
            }
          }
        }
        EOF
