name: Update Gist with Blacklist

on:
  push:
    paths:
      - Blacklist.conf

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Update Gist with new blacklist.conf
      run: |
        CONTENT=$(cat Blacklist.conf)
        curl -X PATCH "https://api.github.com/gists/eb64b490552a0df8d3e7b8b533274a0d" \
        -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
        -d "$(jq -n --arg content "$CONTENT" '{files: {"Blacklist.conf": {content: $content}}}')"
